// <auto-generated />
using MarketStockSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketStockSystem.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20200721154740_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MarketStockSystem.Entities.Acao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<string>("CodAtivo")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<double>("CotacaoAtual")
                        .HasColumnType("double");

                    b.Property<double>("DividaLiquida")
                        .HasColumnType("double");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("LucroAnoAnt")
                        .HasColumnType("double");

                    b.Property<double>("PatrimonioLiquido")
                        .HasColumnType("double");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<int>("QuantAcoes")
                        .HasColumnType("int");

                    b.Property<int>("Segmento")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Acoes");
                });
#pragma warning restore 612, 618
        }
    }
}
